### ISSUE TITLE
each searched result repeatedly appear in the page

### ISSUE THREAD

**Issue by Atlasoin** [second-state/smart-contract-search-engine#5]
For example, the two giveaways shown in the page are the same. (tested in this [demo](http://54.66.215.89/index.html))

![Screenshot from 2019-05-14 10-36-47](https://user-images.githubusercontent.com/17843377/57666897-37ea7500-7634-11e9-98a4-516bbca407f0.png)

**Comment by tpmccallum** [comment]
Hi, 
Thank you, yes I agree.
This was due to a change in the _id (I changed the method of creating the hash and therefore the check to see if the item already existed allowed it to be indexed again).
This has been fixed and a new harvest/index is underway.
Thanks again
