### ISSUE TITLE
Add statistics to the ethereum and cmt demo sites

### ISSUE THREAD

**Issue by juntao** [second-state/smart-contract-search-engine#52]
The demo sites should say how many ABIs and how many contracts are indexed so far.

**Comment by tpmccallum** [comment]
This has now been achieved on the TestNet as per the image below.
<img width="599" alt="Screen Shot 2019-07-08 at 9 18 38 pm" src="https://user-images.githubusercontent.com/9831342/60806386-2fdb2b80-a1c6-11e9-8ac6-1cbb79a634ee.png">
The MainNet is still running V1 code, which does not have the separate indices for ABI, and All. When we update the MainNet to the new code base the statistics will then be able to be displayed.

**Comment by tpmccallum** [comment]
This is now part of the es-ss.js
These values can be accessed via a single command (with the API taking care of the index location/name as well as the authentication/access control). 

Just returns a single integer to the es-ss.js call

https://github.com/second-state/es-ss.js#get-abi-count
https://github.com/second-state/es-ss.js#get-all-count
https://github.com/second-state/es-ss.js#get-contract-count

These can now bee seen on both CMT TestNet [1] and ETH MainNet [2]

[1] https://cmt-testnet.search.secondstate.io/
[2] https://ethereum.search.secondstate.io/ethIndex.html
